name: dark-room-chronicles
genre: topdown
screen:
  width: 800
  height: 600
  fps: 30
player:
  symbol: "@"
  hp: 1
  color: [255, 255, 255]
controls:
  up: 273
  down: 274
  left: 276
  right: 275
  primary: 13
  secondary: 32
difficulty:
  easy: {}
  normal: {}
  hard: {}
